modules_dir = "artifacts/"

[[module]]
name = "curl_adapter"
logger_enabled = false
max_heap_size = "10 KiB"

[module.mounted_binaries]
curl = "/usr/bin/curl"

[[module]]
name = "emiss_getter"
logger_enabled = false
max_heap_size = "5 KiB"
